language: python
sudo: required
python:
  - 2.7.12
env:
- SELENIUM_WEBDRIVER=default

before_install:
  - gem install sass --version 3.3.4
install:
  - pip install -e .
  - pip install coveralls
before_script:
  - wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
  - echo $PATH
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python2.7.12/bin/
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - echo "which chromium-browser"
  - echo "which chromedriver"
  - echo $PATH
script:
  - python setup.py test
