language: python
python:
  - 2.7.12
env:
- SELENIUM_WEBDRIVER=default

before_install:
  - gem install sass --version 3.3.4
  - sudo apt-get update
  - sudo apt-get install chromium-chromedriver
install:
  - pip install -e .
  - pip install coveralls
before_script:
  - wget http://chromedriver.storage.googleapis.com/2.10/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python2.7.9/
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 
script:
  - python setup.py test
